package com.pocketforge.mobile.ui

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.pocketforge.mobile.model.AutonomySnapshot
import com.pocketforge.mobile.runtime.AutonomyLocalBridge
import com.pocketforge.mobile.runtime.AutonomyStore
import com.pocketforge.mobile.runtime.AutonomySupervisorService
import java.net.HttpURLConnection
import java.net.URL
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import org.json.JSONObject

class AutonomyViewModel(application: Application) : AndroidViewModel(application) {
    private val store = AutonomyStore(application)
    private val _snapshot = MutableStateFlow(store.readSnapshot())
    val snapshot: StateFlow<AutonomySnapshot> = _snapshot.asStateFlow()

    private val _actionMessage = MutableStateFlow<String?>(null)
    val actionMessage: StateFlow<String?> = _actionMessage.asStateFlow()

    init {
        viewModelScope.launch(Dispatchers.IO) {
            while (isActive) {
                _snapshot.value = store.readSnapshot()
                delay(1_000L)
            }
        }
    }

    fun start() {
        _actionMessage.value = "Starting local autonomy…"
        AutonomySupervisorService.start(getApplication())
    }

    fun stop() {
        _actionMessage.value = "Stopping local autonomy…"
        AutonomySupervisorService.stop(getApplication())
    }

    fun submitTestIncident() {
        viewModelScope.launch(Dispatchers.IO) {
            runCatching {
                val snapshot = store.readSnapshot()
                check(snapshot.paperclipRunning) { "Start local autonomy first" }
                val connection = URL("http://127.0.0.1:${AutonomyLocalBridge.BRIDGE_PORT}/incident").openConnection() as HttpURLConnection
                connection.requestMethod = "POST"
                connection.connectTimeout = 4_000
                connection.readTimeout = 8_000
                connection.doOutput = true
                connection.setRequestProperty("Content-Type", "application/json")
                connection.setRequestProperty("X-PocketForge-Token", store.bridgeToken())
                val payload = JSONObject()
                    .put("title", "PocketForge autonomy smoke test")
                    .put("description", "Synthetic local incident generated by PocketForge to verify Paperclip assignment and Coder wake-up.")
                    .put("priority", "low")
                    .put("workspace", "pocketforge-autonomy")
                    .put("testCommand", "echo 'PocketForge autonomy smoke test'")
                connection.outputStream.use { it.write(payload.toString().toByteArray(Charsets.UTF_8)) }
                val code = connection.responseCode
                val body = (if (code in 200..299) connection.inputStream else connection.errorStream)?.bufferedReader()?.use { it.readText() }.orEmpty()
                connection.disconnect()
                check(code in 200..299) { "Bridge returned HTTP $code: $body" }
                "Smoke incident accepted by the local Paperclip bridge"
            }.onSuccess { _actionMessage.value = it }
                .onFailure { _actionMessage.value = it.message ?: "Smoke incident failed" }
        }
    }
}
