
name: Extract Zip Contents Directly to Root

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Extract zip contents directly to root
        run: |
          ZIP_FILE=$(find . -maxdepth 2 -name "*.zip" | head -n 1)

          if [ -z "$ZIP_FILE" ]; then
            echo "Project files already present at root. No zip file needs extraction."
            exit 0
          fi

          mkdir -p _temp_extract
          unzip -o "$ZIP_FILE" -d _temp_extract

          INNER_DIR=$(find _temp_extract -mindepth 1 -maxdepth 1 -type d | head -n 1)
          
          # GitHub block na kare isliye zip ke andar ke workflows ko exclude karein
          rm -rf "$INNER_DIR/.github"

          shopt -s dotglob
          echo "Moving contents to root..."
          cp -rf "$INNER_DIR"/* .

          rm -rf _temp_extract
          rm "$ZIP_FILE"

      - name: Commit and Push changes to main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add .

          if git diff --staged --quiet; then
            echo "Koi naya badlaav nahi mila."
          else
            git commit -m "Extracted project to root [skip ci]"
            git push
          fi
